# Generated by Django 5.2.3 on 2025-07-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='source',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
