# Generated by Django 5.2.3 on 2025-08-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('date_posted', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scholarship Post',
                'verbose_name_plural': 'Scholarship Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
