# Generated by Django 5.2.3 on 2025-08-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_scholarshippost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarshippost',
            options={},
        ),
        migrations.RemoveField(
            model_name='scholarshippost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scholarshippost',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='scholarshippost',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='scholarshippost',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='scholarshippost',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='scholarshippost',
            name='source',
            field=models.CharField(default='SmartyAcad', max_length=50),
        ),
    ]
