# Generated by Django 5.2.3 on 2025-08-03 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_scholarshippost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarshippost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Scholarship Post', 'verbose_name_plural': 'Scholarship Posts'},
        ),
        migrations.AddField(
            model_name='scholarshippost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarshippost',
            name='date_posted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarshippost',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scholarshippost',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshippost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scholarshippost',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
