# Generated by Django 5.2.3 on 2025-08-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_course_code_alter_course_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='date_posted',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.TextField(),
        ),
    ]
