const ScholarshipsPage = () => {
    return <h1>WE WOULD USE OUR API TO GET THE HTMLS FROM THE WEBSITES AND THEN USE BEAUTIFUL SOUP TO CONVERT IT TO TITLE AND BODY AND LINKSL</h1>}
export default ScholarshipsPage;